#!/bin/bash
# Short desc.: add a new post to the blog.
# Usage: ./newpost <post title>

# Define variables
time=$(date +%m/%d)
year=$(date +%Y)
basedir="$HOME/ltlnx.github.io"
currentpost="$(date +%m%d)-$(echo "$*" | sed "s| |-|").html"
echo $currentpost
lastpost="$(ls $basedir/posts/2021 | grep [0-9] | tail -1)"

# Copy template to new post
cp "$basedir/posts/template.html" "$basedir/posts/$year/$currentpost"

# Update footer
sed -i -e "s|TITLE|$1|" -e "s|LASTPOST|$lastpost|" -e "s|TIME|$time|" "$basedir/posts/$year/$currentpost"
sed -i "s|<span>　　　</span>|<a href=\"$currentpost\">下一篇</a>|" "$basedir/posts/2021/$lastpost"

