#!/bin/bash
# Short desc.: add a new post to the blog.
# Variables: 
# 1)title: title of the post, date (mm/dd) automatically added
# 2)
basedir="$HOME/ltlnx.github.io"
currentpost="$(date +%m%d)-$1.html"
time="$(date +%m/%d)"
lastpost="$(ls $basedir/posts/$(date +%Y) | grep [0-9] | tail -1)"
cp "$basedir/posts/template.html" "$basedir/posts/$(date +%Y)/$currentpost"
sed -i -e "s/TITLE/$1/" -e "s/LASTPOST/$lastpost/" -e "s|TIME|$time|" $currentpost
sed -i "s|<span>　　　</span>|<a href=\"$currentpost\">下一篇</a>|" $lastpost

