#!/bin/bash
SOURCEDIR="/Users/litelinux/Documents/GitHub/ltlnx.github.io/posts"
cd $SOURCEDIR
# url configuration
URL="https://ltlnx.github.io/posts/"

# values: always hourly daily weekly monthly yearly never
# FREQ="weekly" removed for it is unused

# begin new sitemap
exec 1> index.html

# print head
cat header.html
# print urls
IFS=$'\r\n' GLOBIGNORE='*' command eval "OPTIONS=($(cat $0_options))"
echo "<h5>2021</h5>"
cd 2021
gfind . -type f "${OPTIONS[@]}" -printf "%TY-%Tm-%Td%p\n" | sort -r -k11 | \
while read -r line; do
  FILE=${line:12}
  DATE=$(cat ${FILE} | grep "<small class=\"time\">" )
  TITLE=$(cat ${FILE} | grep "<h1>" | sed -e 's/<h1>//' -e 's/<br>//' -e 's.</h1>..')
  echo "<li>"
  echo "	$DATE"
  echo "	<a href="${URL}2021/${FILE}">$TITLE</a>"
  echo "</li>"
done
echo "<h5>Misc</h5>"
cd ../misc
gfind . -type f "${OPTIONS[@]}" -printf "%TY-%Tm-%Td%p\n" | sort -r -k11 | \
while read -r line; do
  FILE=${line:12}
  DATE=$(cat ${FILE} | grep "<small class=\"time\">" )
  TITLE=$(cat ${FILE} | grep "<h1>" | sed -e 's/<h1>//' -e 's/<br>//' -e 's.</h1>..')
  echo "<li>"
  echo "	$DATE"
  echo "	<a href="${URL}misc/${FILE}">$TITLE</a>"
  echo "</li>"
done
cd ..
# print foot
cat footer.html
